import { createHash, randomUUID } from 'node:crypto';
import { createServer } from 'node:http';

const port = Number(process.env.VOICE_API_PORT || 5050);
const trainedVoices = new Map();

function sendJson(response, statusCode, payload) {
  response.writeHead(statusCode, {
    'Content-Type': 'application/json',
    'Access-Control-Allow-Origin': '*',
    'Access-Control-Allow-Methods': 'POST, OPTIONS',
    'Access-Control-Allow-Headers': 'Content-Type',
  });
  response.end(JSON.stringify(payload));
}

function readBody(request) {
  return new Promise((resolve, reject) => {
    const chunks = [];
    request.on('data', (chunk) => chunks.push(chunk));
    request.on('end', () => resolve(Buffer.concat(chunks)));
    request.on('error', reject);
  });
}

function extractFilename(body) {
  const head = body.subarray(0, Math.min(body.length, 2048)).toString('utf8');
  const match = head.match(/filename="([^"]+)"/i);
  return match?.[1] || 'voice-sample';
}

async function handleTrain(request, response) {
  const body = await readBody(request);
  if (!body.length) {
    sendJson(response, 400, { error: 'Voice sample file is required.' });
    return;
  }

  const fileName = extractFilename(body);
  const fingerprint = createHash('sha256').update(body).digest('hex').slice(0, 16);
  const voiceId = `local-${fingerprint}-${randomUUID().slice(0, 8)}`;

  trainedVoices.set(voiceId, {
    fileName,
    fingerprint,
    trainedAt: new Date().toISOString(),
  });

  sendJson(response, 200, {
    voiceId,
    name: fileName,
    mode: 'local-development-registration',
    message:
      'Voice sample received by the local API. Configure a voice cloning provider in this endpoint to create a real cloned voice model.',
  });
}

async function handleSynthesize(request, response) {
  const body = await readBody(request);
  let payload = {};

  try {
    payload = JSON.parse(body.toString('utf8') || '{}');
  } catch {
    sendJson(response, 400, { error: 'Invalid JSON body.' });
    return;
  }

  if (!payload.voiceId || !trainedVoices.has(payload.voiceId)) {
    sendJson(response, 404, { error: 'Train a voice sample before synthesis.' });
    return;
  }

  sendJson(response, 501, {
    error:
      'Synthesis provider is not configured. The local API registered the uploaded sample, but cloned speech audio must be generated by a provider such as ElevenLabs, Azure Speech custom voice, or another TTS cloning service.',
    voiceId: payload.voiceId,
  });
}

const server = createServer(async (request, response) => {
  if (request.method === 'OPTIONS') {
    sendJson(response, 204, {});
    return;
  }

  try {
    if (request.method === 'POST' && request.url === '/api/voice/train') {
      await handleTrain(request, response);
      return;
    }

    if (request.method === 'POST' && request.url === '/api/voice/synthesize') {
      await handleSynthesize(request, response);
      return;
    }

    sendJson(response, 404, { error: 'Voice API route not found.' });
  } catch (error) {
    sendJson(response, 500, {
      error: error instanceof Error ? error.message : 'Unexpected voice API error.',
    });
  }
});

server.listen(port, '127.0.0.1', () => {
  console.log(`Voice API listening on http://127.0.0.1:${port}`);
});
